//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discans.Resources.Modules.Alert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivateAlertModuleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivateAlertModuleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discans.Resources.Modules.Alert.PrivateAlertModuleResource", typeof(PrivateAlertModuleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ```ini
        ///Manga: [{0}]
        ///Last release: [{1}]
        ///Based on: [{2}]
        ///```.
        /// </summary>
        internal static string AlertListChunck {
            get {
                return ResourceManager.GetString("AlertListChunck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You alerts:.
        /// </summary>
        internal static string AlertListTitle {
            get {
                return ResourceManager.GetString("AlertListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no alerts :(.
        /// </summary>
        internal static string NoAlerts {
            get {
                return ResourceManager.GetString("NoAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will stop to receive notifications of that manga..
        /// </summary>
        internal static string UserAlertRemove {
            get {
                return ResourceManager.GetString("UserAlertRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok! You are going to receive an alert after a new release of this manga!
        ///You can also check your private alert list using the follow command `{0}`
        ///
        ///This alert form contains the following informations:
        ///```ini
        ///Manga name: [{1}]
        ///Last released chapter: [{2}]
        ///Based on: [{3}]
        ///```.
        /// </summary>
        internal static string UserAlertSuccess {
            get {
                return ResourceManager.GetString("UserAlertSuccess", resourceCulture);
            }
        }
    }
}
