//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discans.Resources.Modules.Alert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerAlertModuleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerAlertModuleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discans.Resources.Modules.Alert.ServerAlertModuleResource", typeof(ServerAlertModuleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no server alert or user alert here :/.
        /// </summary>
        internal static string ServerAlertListAllEmpty {
            get {
                return ResourceManager.GetString("ServerAlertListAllEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here all alerts for this server:.
        /// </summary>
        internal static string ServerAlertListAllMessageHeader {
            get {
                return ResourceManager.GetString("ServerAlertListAllMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ```ini
        ///Manga: [{0}]
        ///Who will be alerted: [all from &apos;{1}&apos;]
        ///Last release: [{2}]
        ///Based on: [{3}]
        ///```.
        /// </summary>
        internal static string ServerAlertListAllMessageItem {
            get {
                return ResourceManager.GetString("ServerAlertListAllMessageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no server alert here :(.
        /// </summary>
        internal static string ServerAlertListEmpty {
            get {
                return ResourceManager.GetString("ServerAlertListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurated alerts directly for this server mention:.
        /// </summary>
        internal static string ServerAlertListMessageHeader {
            get {
                return ResourceManager.GetString("ServerAlertListMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ```ini
        ///Manga: [{0}]
        ///Last Release: [{1}]
        ///Based on: [{2}]
        ///```.
        /// </summary>
        internal static string ServerAlertListMessageItem {
            get {
                return ResourceManager.GetString("ServerAlertListMessageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All project and user alers will no more be sent in this server. I will miss you :´(.
        /// </summary>
        internal static string ServerAlertRemoveAllConfirmSuccess {
            get {
                return ResourceManager.GetString("ServerAlertRemoveAllConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will REMOVE ALL ALERTS in your server - it can be User Alerts and Server Alerts. Are you sure?
        ///
        ///If you are, type `{0}`..
        /// </summary>
        internal static string ServerAlertRemoveAllMessage {
            get {
                return ResourceManager.GetString("ServerAlertRemoveAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server will no more be alerted about that release..
        /// </summary>
        internal static string ServerAlertRemoveSuccess {
            get {
                return ResourceManager.GetString("ServerAlertRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I got it!
        ///After a new release I will alert you!
        ///
        ///This register contains the following informations :
        ///```ini
        ///Mangá name: [{0}]
        ///Users to be alerted: [All server users]
        ///Last release: [{1}]
        ///Based on: [{2}]
        ///```.
        /// </summary>
        internal static string ServerAlertSuccess {
            get {
                return ResourceManager.GetString("ServerAlertSuccess", resourceCulture);
            }
        }
    }
}
